### ISSUE TITLE
Error when installing for first time

### ISSUE THREAD

**Issue by benjamin-daniel** [rainbow-me/rainbow#1137]
I keep getting this error.
<img width="895" alt="image" src="https://user-images.githubusercontent.com/19100745/94325215-3ef9f500-ff95-11ea-93cd-609a762a9156.png">

**Comment by WataruKay** [comment]
currently facing the same issue after following the setup instructions

**Comment by nntruong96** [comment]
I have a same problem.

**Comment by cawfree** [comment]
This is probably because you're missing a `.env` file in the application root (you'll probably see `yarn` complain with `⚠️ .env file missing!! ⚠️` when initializing the project).

You can see this stage in the [`postinstall`](https://github.com/rainbow-me/rainbow/blob/433de143c85bf0f1f5bd5227fbbfae536892d849/scripts/postinstall.sh#L16) script, where the files are automatically generated. This gets execute after the project dependencies have been initially downloaded.

Next, you'll need to initialize the `.env`:

```sh
ENABLE_DEV_MODE=
IS_TESTING=
ETHERSCAN_API_KEY=
BRANCH=
DEV_SEEDS=
GANACHE_URL=
DATA_API_KEY=
DATA_ORIGIN=
INFURA_PROJECT_ID=
INFURA_PROJECT_ID_DEV=
RAINBOW_WYRE_MERCHANT_ID=
RAINBOW_WYRE_MERCHANT_ID_TEST=
WYRE_ACCOUNT_ID=
WYRE_ACCOUNT_ID_TEST=
WYRE_ENDPOINT=
WYRE_ENDPOINT_TEST=
WYRE_TOKEN=
WYRE_TOKEN_TEST=
REACT_APP_SEGMENT_API_WRITE_KEY=
SENTRY_ENDPOINT=
SENTRY_ENVIRONMENT=
ETH_GAS_STATION_API_KEY=
RAINBOW_MASTER_KEY=
```

I'm currently working on figuring out some sensible defaults for these.

Next, you might be prevented from making a build because of a missing `ReaHeader.h`. This looks like it may be imported incorrectly (this file may have recently been moved), so you can delete this import from the Project Explorer and then point it at the `ReaHeader.h` file located [here](https://github.com/rainbow-me/rainbow/tree/develop/ios/Config).

Finally, XCode may complain about a missing build input file. You can work around this by opting to use the [Legacy Build System](https://stackoverflow.com/questions/52401856/problems-after-upgrading-to-xcode-10-build-input-file-cannot-be-found) for the workspace.

**Comment by skylarbarrera** [comment]
Hey everybody, thanks for you interest in Rainbow 🌈 !!   
We've been working to make our repo more accessible and will continue to do so going forward!

For those of you still looking to build our project please refer to this PR and follow our updated README & env.example!

https://github.com/rainbow-me/rainbow/pull/1262
