### ISSUE TITLE
Testnets

### ISSUE THREAD

**Issue by simibac** [rainbow-me/rainbow#1246]
I have test Ethers on Ropsten and in Rinkeby. But the wallet does not display the transfer button.

Also connecting a dApp with wallet connect does not work in either of the network. The error is shown in the images.

<p float="left">
  <img src="https://user-images.githubusercontent.com/15369592/97488023-fcde1d80-195d-11eb-9e63-d2e05e547b73.jpeg" width="400" />
  <img src="https://user-images.githubusercontent.com/15369592/97487792-a07afe00-195d-11eb-983f-88d9bc7c1a16.PNG" width="400" /> 
  <img src="https://user-images.githubusercontent.com/15369592/97487801-a40e8500-195d-11eb-89d9-7b62bf0b4860.PNG" width="400" />
</p>

**Comment by skylarbarrera** [comment]
Hey @simibac, Thanks for using 🌈 ! From the looks of it this was due to our testnet data providers being down, can you confirm that everything is working now? If its still an issue let us know and we'll look into it further!  We're continuing to improve our data reliability so hopefully this wont happen moving forward!
