### ISSUE TITLE
UX: show a loading indicator when connecting with WalletConnect from a deep link

### ISSUE THREAD

**Issue by hazae41** [rainbow-me/rainbow#2021]
Sometimes, WalletConnect takes time to connect, and the app doesn't show anything meaningful until the connection is established.

It would be a better UX to show at least a loading indicator, showing that the app is currently trying to connect to the bridge or to the dapp.

The same thing happens for transactions and signatures requests.

**Comment by brunobar79** [comment]
Thanks for reporting this.

Unfortunately this is not possible with the current architecture of WalletConnect. We're not "trying" to connect or anything like that, we just listen to requests from the dapp forwarded by the WC bridge. If we don't show the request is because we didn't hear about it.

This is a know problem related to the scaling issues that WalletConnect v1 is facing, which are solved in WalletConnect v2. 

We'll start working on supporting WalletConnect v2 next week and expect to have it production ready by in about a month or so.

Stay tuned!
