### ISSUE TITLE
Wallet name change has no effect

### ISSUE THREAD

**Issue by cloudhead** [rainbow-me/rainbow#2141]
Trying to edit a wallet name through the "Edit Wallet" option has no effect. The wallet keeps its original name.

**Comment by nicoglennon** [comment]
Hi @cloudhead, this was fixed in this PR: https://github.com/rainbow-me/rainbow/commit/920d1b70e503f9c801b4b7db646fccd8d0e5bd06#diff-fe71a13d8224043e698676604f5c7b46a1418cec679014c20c9ded7ba878b9cfR223. 

We were using `Array.prototype.some()` to find the wallet to update, but the function passed into `some` was async so would always return a Promise and thus was always truthy on the first value. Should work now!

**Comment by cloudhead** [comment]
Aha great, thanks!
