### ISSUE TITLE
Transaction pending (and impossible to monitor on etherscan)

### ISSUE THREAD

**Issue by Garennelelapin** [rainbow-me/rainbow#2448]
Hello!

I have the same issue as this bug : https://github.com/rainbow-me/rainbow/issues/2396
I executed a swap on Uniswap, and my wallet is still "pending". I can not cancel it, I can not speed it up, and I can not see the transaction on etherscan. I also have the necessary amount of ETH to finance the swap.

I can put a screenshot if necessary!
Thanks a lot

**Comment by sandracole1710** [comment]
I can help you resolve this issue email me on sandracole1710@gmail.com

**Comment by skylarbarrera** [comment]
Hey @Garennelelapin,

We've since added a bunch of fixes to ensure this doesn't happen moving forward. A few things we have added that should help:

- Local Nonce Tracking: https://github.com/rainbow-me/rainbow/commit/be09bac500f4602f55f7c0dc33bc9a5be8786c4f
- EIP-1559 (releasing next week): https://github.com/rainbow-me/rainbow/pull/2422

🌈
