### ISSUE TITLE
Support for eth_getEncryptionPublicKey and eth_decrypt

### ISSUE THREAD

**Issue by shawnmitchell** [rainbow-me/rainbow#2787]
I see that `@metamask/eth-sig-util` is already a dependency in the project. Any thoughts on beating metamask mobile to the punch and supporting `eth_getEncryptionPublicKey` and `eth_decrypt` functions?

**Comment by shawnmitchell** [comment]
Let's not let this get stale! I think this would be a great addition to Rainbow. Anyone on the team have any thoughts?

**Comment by gnewfield** [comment]
I agree! These methods are essential to my use-case. I think they're strongly aligned with the purpose of a wallet application, which is to securely store the user's keys and provide robust APIs for generating signatures and performing asymmetric encryption.

After looking around various forums, it seems that I am not alone in wanting this functionality. Furthermore, it seems that - due to the lack of such functionality - developers are resorting to implementing their own workarounds, which is definitely suboptimal in terms of security and standardization.

**Comment by conor-deegan** [comment]
Would be great to get an update on this. Definitely needed.

**Comment by avivash** [comment]
Hey, any chance we can re-open this issue, please? I also need this for a use case I'm working on, thanks!
