### ISSUE TITLE
Rainbow wallet shows error message "Uh oh! We couldn't recognize this URL!" on `WalletConnect#signPersonalMessage`

### ISSUE THREAD

**Issue by jamiely** [rainbow-me/rainbow#2852]
While attempting to use WalletConnect's (1.7.0) `signPersonalMessage` function after connecting successfully, I got the following error:

```
Uh oh! We couldn't recognize this URL!
```

iOS simulator with Rainbow wallet master branch:

![image](https://user-images.githubusercontent.com/187039/150188797-50cb5235-d742-4476-9e9f-c199801214f5.png)

_Note: This error above has been modified to show the URL._

iOS device (I think version 1.6.1 of Rainbow):

![image](https://user-images.githubusercontent.com/187039/150187234-2dd7fd05-5196-412f-8bc0-e72de8b6e294.png)

It seems like when a connect request is made, the URL looks like:
```json
{"action": "wc", "pathname": "/wc", "url": "https://rnbwapp.com/wc?uri=wc%***&redirectUrl=***", "what": "Handling deeplink"}
```

But the signPersonalMessage request doesn't have the `wc` portion of the deep link.
```json
{"action": "", "pathname": "/", "url": "https://rnbwapp.com", "what": "Handling deeplink"}
```

**Comment by estebanmino** [comment]
hey @jamiely, which dapp are you using?

**Comment by intergalacticspacehighway** [comment]
@estebanmino we're facing this issue at showtime. The [deeplink here](https://github.com/rainbow-me/rainbow/blob/develop/src/handlers/deeplinks.ts#L41) checks for `wc` in path but sign requests are [sent without wc](https://github.com/WalletConnect/walletconnect-monorepo/blob/v1.0/packages/helpers/react-native-dapp/src/providers/WalletConnectProvider.tsx#L207) and [connection request](https://github.com/WalletConnect/walletconnect-monorepo/blob/v1.0/packages/helpers/react-native-dapp/src/providers/WalletConnectProvider.tsx#L118) includes wc in path (so alert doesn't show up for connect request)

I guess removing the Alert should fix it because we don't need to handle this deeplink request as I guess it'll be handled in the `call_request` handler.

**Comment by intergalacticspacehighway** [comment]
Also unrelated to this issue but curious if are there any instances reported of signing requests not reaching rainbow? 
It uses socket and I am afraid app can miss it if it's in [background](https://www.reddit.com/r/reactnative/comments/bj10hf/react_native_handle_socket_connections_events/). We've seen it happen quite often. We'll dig more and report if needed.

**Comment by jamiely** [comment]
@estebanmino sorry I never replied, it is an unreleased dapp unfortunately. It looks like you may have a fix anyway.

**Comment by jamiely** [comment]
@intergalacticspacehighway This might be useful to you: https://github.com/WalletConnect/walletconnect-monorepo/pull/732. It seems like this was the cause of the uh oh message.
