### ISSUE TITLE
What info do I need from .env for the app to work?

### ISSUE THREAD

**Issue by jvazgot** [rainbow-me/rainbow#3619]
I see that the readme doesn't specify which variables are needed on the .env.
I've been having some issues with the app. For example this one when importing or creating a wallet

`Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]' was thrown while invoking setInternetCredentialsForServer on target RNKeychainManager with params (
    signingWallet,
    signingWallet,
    "<null>",
        {
        accessible = AccessibleWhenUnlockedThisDeviceOnly;
    },
    14666,
    14667`

**Comment by stefannovak** [comment]
Agreed, why am I supposed to guess what 'GOOGLE_SERVICE_API_KEY' is? What are 

```
DATA_ENDPOINT=
DATA_ORIGIN=
DATA_API_KEY=
```
??

Eth Gas Station docs point to broken links with DefiPulse

Clearer docs are needed

**Comment by robgleason** [comment]
I chose the route in the documentation for "a self-provided config for a personal Firebase project". I created a firebase.google project, and used me.rainbow as the bundle id. It gives you a GoogleService-Info.plist with a GOOGLE_SERVICE_API_KEY. I hardcoded GOOGLE_SERVICE_API_KEY in .env and it still pulled that data to update the GoogleService-Info.plist in /rainbow/ios/Frameworks  . That fixed 'GOOGLE_SERVICE_API_KEY' for me, but now my computer is crashing after downloading Xcode/(Apple Developer environment)- because I have 5% of computer memory left and I need to clear up memory space.
